# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20171201_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collection',
            managers=[
            ],
        ),
    ]
